#!/bin/sh

NAME="syncwatch"
SERVICESCRIPT="$NAME.service"
SERVICEDIR="/etc/systemd/system"

if [ -f "$SERVICEDIR/$SERVICESCRIPT" ]; then 
    systemctl stop $SERVICESCRIPT
    systemctl disable $SERVICESCRIPT
fi

exit 0
